---
version: 1.7.0
slug: dnsmasq
name: Dnsmasq Custom
description: A simple DNS server
url: https://github.com/jaco512/custom-dnsmasq
advanced: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: homeassistant/{arch}-addon-dnsmasq
init: false
options:
  defaults:
    - 9.9.9.9
    - 149.112.112.112
  forward-max: 500
  forwards: []
  hosts: []
  services: []
  cnames: []
  log_queries: false
ports:
  53/tcp: 53
  53/udp: 53
schema:
  defaults:
    - str
  forward-max: int
  forwards:
    - domain: str
      server: str
  hosts:
    - host: str
      ip: str
  services:
    - host: str
      port: str
      priority: int
      srv: str
      weight: int
  cnames:
    - name: str
      target: str
  log_queries: bool
startup: system
